name: Kittygram CI/CD

on:
  push:
  pull_request:
    branches: [ main ]

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install backend deps
        working-directory: ./backend
        run: |
          sudo apt-get update && sudo apt-get install -y \
            gcc \
            libjpeg-dev \
            libpng-dev \
            libwebp-dev \
            libtiff-dev \
            libfreetype6-dev \
            liblcms2-dev \
            libopenjp2-7-dev \
            libzip-dev \
            libpq-dev \
            && sudo rm -rf /var/lib/apt/lists/* \
            && python -m pip install --upgrade pip \
            && pip install -r requirements.txt \
            && pip install ruff pycodestyle

      - name: Run Ruff check
        working-directory: ./backend
        run: ruff check .

      - name: Run Ruff format check
        working-directory: ./backend
        run: ruff format --check .

      - name: Run pycodestyle
        working-directory: ./backend
        run: pycodestyle .

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install frontend deps
        working-directory: ./frontend
        run: |
          npm ci

      - name: Run frontend tests
        working-directory: ./frontend
        run: |
          npm test -- --watch=false

  build_and_push:
    needs: tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: backend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/kittygram_backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: frontend/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/kittygram_frontend:latest

      - name: Build and push gateway image
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          file: nginx/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/kittygram_gateway:latest

      - name: Send Telegram notify on success
        if: success()
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ env.TELEGRAM_TO }}
          token: ${{ env.TELEGRAM_TOKEN }}
          message: |
            CI/CD успешно выполнен!
            Автор: ${{ github.actor }}
            Коммит: ${{ github.event.commits[0].message }}
            Ссылка: https://github.com/${{ github.repository }}/commit/${{ github.sha }}